version: "3.8"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    env_file:
      - .env
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb2
    ports:
      - 8086:8086
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    env_file:
      - .env
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana_config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_config/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
      - ./grafana_config/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana_config/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - influxdb
  app:
    container_name: app
    build:
      context: .
      args:
        reload: 1
    restart: always
    env_file:
      - .env
    volumes: 
      - ./app:/lhr-pi/app
    depends_on:
      - grafana
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped 
    env_file:
      - .env
    ports: 
      - 80:80
    volumes:
      - ./nginx_templates:/etc/nginx/templates
    depends_on:
      - app
  hostapd:
    container_name: hostapd
    image: offlinehacker/docker-ap:latest
    restart: unless-stopped
    privileged: True
    network_mode: "host"
volumes: 
  influxdb:
  grafana_storage: