{
 "title": "BPS - Longhorn Racing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "100ms",
 "panels": [
  {
   "title": "Max Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Temperature\")\r\n  |> last()\r\n  |> highestMax(n:1, column: \"_value\", groupColumns: [])\r\n  |> group(columns: [\"instance\"])"
    }
   ]
  },
  {
   "title": "Min Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Temperature\")\r\n  |> last()\r\n  |> lowestMin(n:1, column: \"_value\", groupColumns: [])\r\n  |> group(columns: [\"instance\"])"
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"State of Charge\" and\r\n    r._field == \"Battery\"\r\n  )"
    }
   ]
  },
  {
   "title": "Supplemental Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Voltage\" and\r\n    r._field == \"Supplemental\"\r\n  )"
    }
   ]
  },
  {
   "title": "Supplemental Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Voltage\" and\r\n    r._field == \"Supplemental\"\r\n  )"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Temps",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Temperature\" and\r\n    r._field == \"Object 1\"\r\n  )"
      },
      {
       "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Temperature\" and\r\n    r._field == \"Object 2\"\r\n  )"
      }
     ]
    },
    {
     "title": "Object 1's Temperature",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 9, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Temperature\" and\r\n    r._field == \"Object 1\"\r\n  )"
      }
     ]
    },
    {
     "title": "Object 2's Temperature",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Temperature\" and\r\n    r._field == \"Object 2\"\r\n  )"
      }
     ]
    }
   ]
  },
  { "title": "Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Object 1's Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Voltage\" and\r\n    r._field == \"Object 1\"\r\n  )"
    }
   ]
  },
  {
   "title": "Object 2's Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Voltage\" and\r\n    r._field == \"Object 2\"\r\n  )"
    }
   ]
  },
  {
   "title": "Object's 1 Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Voltage\" and\r\n    r._field == \"Object 1\"\r\n  )"
    }
   ]
  },
  {
   "title": "Object's 2 Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"LHR\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Voltage\" and\r\n    r._field == \"Object 2\"\r\n  )"
    }
   ]
  }
 ]
}